commit_message: "[skip ci] [Commit by Crowdin]"
files:
  - source: /gluco-check-common/strings/en-US/*
    translation: /gluco-check-common/strings/%locale%/%original_file_name%
  - source: /gluco-check-frontend/public/locales/en/translation.json
    translation: /gluco-check-frontend/public/locales/%two_letters_code%/translation.json
