localizedSettings:
  developerEmail: niels@glucocheck.app
  developerName: Niels Maerten
  displayName: Gluco Check
  fullDescription: |-
    Gluco Check porta Nightscout sul tuo Assistente Google. Chiedi il tuo attuale livello di glicemia, quanti carboidrati hai, quando hai cambiato il sensore l'ultima volta e altro ancora.

    Prima di poter utilizzare Gluco Check devi collegare il tuo sito Nightscout su: https://glucocheck.app

    Nota: le informazioni fornite da Gluco Check non sostituiscono le indicazioni del medico.
  privacyPolicyUrl: https://glucocheck.app/terms/it-IT
  pronunciation: Gluco Check
  sampleInvocations:
  - Parla a Gluco Check
  - Chiedi a Gluco Check quanto è vecchio il mio sensore
  - Chiedi a Gluco Check di leggere la mia glicemia
  - Chiedi a Gluco Check di leggere i miei carboidrati
  shortDescription: Chiedi a Google di leggere la tua glicemia da Nightscout
  smallLogoImage: https://lh3.googleusercontent.com/iByZN58udeU-Y00jiCeY5I5piOdBaxzPRutPS1DAO8rhTd2rJJvc55t6aUzkM7b0833W9tAeK4mvlA
  termsOfServiceUrl: https://glucocheck.app/terms/it-IT
  voice: female_1
