export default {
  status: 'ok',
  name: 'nightscout',
  version: '14.0.7',
  serverTime: '2020-12-06T20:27:16.568Z',
  serverTimeEpoch: 1607286436568,
  apiEnabled: true,
  careportalEnabled: true,
  boluscalcEnabled: false,
  settings: {
    units: 'mg/dl',
    timeFormat: 24,
    nightMode: false,
    editMode: true,
    showRawbg: 'never',
    customTitle: 'Nightscout Mock Server',
    theme: 'colors',
    alarmUrgentHigh: false,
    alarmUrgentHighMins: [30, 60, 90, 120],
    alarmHigh: false,
    alarmHighMins: [30, 60, 90, 120],
    alarmLow: false,
    alarmLowMins: [15, 30, 45, 60],
    alarmUrgentLow: false,
    alarmUrgentLowMins: [15, 30, 45],
    alarmUrgentMins: [30, 60, 90, 120],
    alarmWarnMins: [30, 60, 90, 120],
    alarmTimeagoWarn: false,
    alarmTimeagoWarnMins: '15',
    alarmTimeagoUrgent: false,
    alarmTimeagoUrgentMins: '30',
    alarmPumpBatteryLow: false,
    language: 'en',
    scaleY: 'linear',
    showPlugins: 'careportal basal iob cob openaps pump cage sage delta direction upbat',
    showForecast: 'openaps',
    focusHours: 3,
    heartbeat: 60,
    baseURL: '',
    authDefaultRoles: 'readable',
    thresholds: {
      bgHigh: 190,
      bgTargetTop: 155,
      bgTargetBottom: 70,
      bgLow: 55,
    },
    insecureUseHttp: false,
    secureHstsHeader: true,
    secureHstsHeaderIncludeSubdomains: false,
    secureHstsHeaderPreload: false,
    secureCsp: false,
    deNormalizeDates: false,
    showClockDelta: false,
    showClockLastTime: false,
    bolusRenderOver: 1,
    frameUrl1: '',
    frameUrl2: '',
    frameUrl3: '',
    frameUrl4: '',
    frameUrl5: '',
    frameUrl6: '',
    frameUrl7: '',
    frameUrl8: '',
    frameName1: '',
    frameName2: '',
    frameName3: '',
    frameName4: '',
    frameName5: '',
    frameName6: '',
    frameName7: '',
    frameName8: '',
    DEFAULT_FEATURES: [
      'bgnow',
      'delta',
      'direction',
      'timeago',
      'devicestatus',
      'upbat',
      'errorcodes',
      'profile',
      'dbsize',
      'runtimestate',
      'basal',
      'careportal',
    ],
    alarmTypes: ['simple'],
    enable: [
      'careportal',
      'basal',
      'cors',
      'iob',
      'cob',
      'openaps',
      'pump',
      'sage',
      'cage',
      'treatmentnotify',
      'bgnow',
      'delta',
      'direction',
      'timeago',
      'devicestatus',
      'upbat',
      'errorcodes',
      'profile',
      'dbsize',
      'runtimestate',
      'simplealarms',
    ],
  },
  extendedSettings: {
    openaps: {
      colorPredictionLines: true,
    },
    basal: {
      render: 'icicle',
    },
    devicestatus: {
      advanced: true,
      days: 1,
    },
  },
  authorized: {
    token: 'abcxyz',
    sub: 'gluco-check',
    permissionGroups: [['api:*:read'], ['*:*:read']],
    iat: 1608753230,
    exp: 1608756830,
  },
  runtimeState: 'loaded',
};
