accountLinking:
  enableAccountCreation: true
  linkingType: GOOGLE_SIGN_IN
defaultLocale: en
localizedSettings:
  displayName: Gluco Check
  pronunciation: Gluco Check
  voice: female_1
projectId: gluco-check-prod
