accountLinking:
  enableAccountCreation: true
  linkingType: GOOGLE_SIGN_IN
defaultLocale: en
localizedSettings:
  displayName: Gluco Nightly
  pronunciation: Gluco Nightly
  voice: female_1
projectId: gluco-check-nightly
