localizedSettings:
  developerEmail: niels@glucocheck.app
  developerName: Niels Maerten
  displayName: Gluco Check
  fullDescription: "Gluco Check bringt Nightscout auf Ihren Google Assistant. Fragen Sie nach Ihrem aktuellen Blutzuckerspiegel, wie viele Kohlenhydrate Sie an Bord haben, wann Sie Ihren Sensor zuletzt gewechselt haben und vieles mehr. \n\nBevor Sie Gluco Check nutzen können, müssen Sie Ihre Nightscout-Seite auf https://glucocheck.app verlinken.\n\nHinweis: Die von Gluco Check bereitgestellten Informationen sind kein Ersatz für die Beratung durch einen Arzt."
  privacyPolicyUrl: https://glucocheck.app/terms/de-DE
  pronunciation: Gluco Check
  sampleInvocations:
  - Mit Gluco Check sprechen
  - Frage Gluco Check, wie alt mein Sensor ist
  - Frage Gluco Check meinen Blutzucker auszulesen
  - Gluco Check bitten, meine Carbs an Bord zu lesen
  shortDescription: Frage Google nach deinem Blutzucker auf Nightscout
  smallLogoImage: https://lh3.googleusercontent.com/qhE7FiMfd4EhToY6GyEl6_Cy-OXyTaMtW3-DvcajAMog4OeJX1bgPvoYkJCiYULGOS0uNEgOarGr
  termsOfServiceUrl: https://glucocheck.app/terms/de-DE
  voice: female_1
