accountLinking:
  enableAccountCreation: true
  linkingType: GOOGLE_SIGN_IN
category: HEALTH_AND_FITNESS
defaultLocale: en
localizedSettings:
  developerEmail: niels@glucocheck.app
  developerName: Niels Maerten
  displayName: Gluco Check
  fullDescription: |-
    Gluco Check brings Nightscout to your Google Assistant. Ask for your current blood sugar level, how many carbs you've got on board, when you last changed your sensor, and more.

    Before you can use Gluco Check you must link your Nightscout site on: https://glucocheck.app

    Note: The information provided by Gluco Check is not a substitute for advice from a medical professional.
  privacyPolicyUrl: https://glucocheck.app/terms
  pronunciation: Gluco Check
  sampleInvocations:
    - Talk to Gluco Check
    - Ask Gluco Check how old my sensor is
    - Ask Gluco Check to read my glucose
    - Ask Gluco Check to read my carbs on board
  shortDescription: Ask Google to read your blood sugar from Nightscout
  smallLogoImage: https://lh3.googleusercontent.com/iByZN58udeU-Y00jiCeY5I5piOdBaxzPRutPS1DAO8rhTd2rJJvc55t6aUzkM7b0833W9tAeK4mvlA
  termsOfServiceUrl: https://glucocheck.app/terms
  voice: female_1
projectId: gluco-check-prod
testingInstructions: |-
  Hi!

  Context: "Nightscout" is a webapp used to collect data such as glucose levels, amount of carbs eaten, etc.
  "Gluco Check" (this Action) allows accessing this info using the Assistant.

  Testing instructions: Before you can test, you'll need to connect a Nightscout site.
  1. Visit https://glucocheck.app and sign in. Any Google account will do.
  Note: If you're using an 'aog.platform.***@gmail.com' account, we will automatically populate it with test data.
  Using another account? Follow these steps:
  2. Click the 'Link your Nightscout' button
  3. In the field "Nightscout URL", enter: "https://cgm.example.com" @TODO
  4. In the field "Token", enter: "aogreview-daf8b883ffbeef3b" @TODO
  5. Click Save

  Done! You can now invoke the action.
