// TODO: Delete this file
/* eslint-disable */

// TO ADD A ROLE:
var axios = require('axios');
var qs = require('qs');
var data = qs.stringify({
  'permissions[]': '*:*:read',
  'notes': 'Auto-generated by Gluco Check (https://glucocheck.app)',
  'name': 'gluco-check'
});
var config = {
  method: 'post',
  url: '/api/v2/authorization/roles/',
  headers: {
    'api-secret': '',
    'Content-Type': 'application/x-www-form-urlencoded',
  },
  data: data
};

axios(config)
  .then(function (response) {
    console.log(JSON.stringify(response.data));
  })
  .catch(function (error) {
    console.log(error);
  });

// TO ADD A SUBJECT:
var axios = require('axios');
var qs = require('qs');
var data = qs.stringify({
  'roles[]': 'gluco-check',
  'notes': 'Auto-generated by Gluco Check (https://glucocheck.app)',
  'name': 'gluco-check'
});
var config = {
  method: 'post',
  url: '/api/v2/authorization/subjects/',
  headers: {
    'api-secret': '',
    'Content-Type': 'application/x-www-form-urlencoded',
  },
  data: data
};

axios(config)
  .then(function (response) {
    console.log(JSON.stringify(response.data));
  })
  .catch(function (error) {
    console.log(error);
  });
