name: Build/Test gluco-check-frontend-client
on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - uses: egordm/gha-yarn-node-cache@v1
      - name: Install modules
        run: yarn install
      - name: Build
        run: yarn build
        env:
          CI: true
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - uses: egordm/gha-yarn-node-cache@v1
      - name: Install modules
        run: yarn install
      - name: Test
        run: yarn test:ci
      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
