name: Build, Test, Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
      name: Cloning repository
    - name: Using Node.js v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn # Includes Typescript build
      name: Installing dependencies
    - run: yarn test # Linting will happen posttest
      name: Running tests
    - run: bash <(curl -s https://codecov.io/bash)
      name: Reporting coverage
