name: Build, Test, Lint, Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      name: Cloning repository
    - name: Using Node.js v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn # Includes Typescript build
      name: Installing components
    - run: yarn test # Linting will happen posttest
      name: Running tests
    - run: bash <(curl -s https://codecov.io/bash)
      name: Reporting coverage
   
    - name: Deploying webhooks
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_PATH: ./gluco-check-webhooks
        PROJECT_ID: nightly
