name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: "[SETUP] Download snapshot"
        uses: actions/download-artifact@v2
        with:
          name: snapshot-${{ github.sha }}-${{ matrix.node-version }}

      - name: "[SETUP] Enable Node v${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Deploy WEBHOOKS"
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./gluco-check-webhooks
          PROJECT_ID: gluco-check-nightly

      - name: "Deploy FRONTEND"
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./gluco-check-frontend
          PROJECT_ID: gluco-check-nightly
