name: Build, Test, Lint, Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Cloning repository
      uses: actions/checkout@v2

    - name: Using Node.js v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing dependencies
      run: yarn # Includes Typescript build

    - name: Running tests
      run: yarn test # Includes linting (post tests)
      
    - name: Reporting coverage
      run: bash <(curl -s https://codecov.io/bash)
  
    - name: Deploying webhooks to nightly
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_PATH: ./gluco-check-webhooks
        PROJECT_ID: nightly
